"""store avatar_hash

Revision ID: 480ed06a2354
Revises: 20f76e015bdc
Create Date: 2016-12-06 14:52:06.584706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480ed06a2354'
down_revision = '20f76e015bdc'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
