"""add User pending_email column

Revision ID: 7b3db26cb538
Revises: ef45035fdf8e
Create Date: 2016-12-01 19:40:21.514236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3db26cb538'
down_revision = 'ef45035fdf8e'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_pending_email'), 'users', ['pending_email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_pending_email'), table_name='users')
    op.drop_column('users', 'pending_email')
    ### end Alembic commands ###
